import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import { cookies } from 'next/headers';
import AuthStore from '@/components/AuthStore';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Book Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get('token');

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthStore isAuth={!!token} />
        <Header />
        {children}
      </body>
    </html>
  );
}
